name: ColorMatch
main: com.comze_instancelabs.colormatch.Main
version: 1.5.2
author: instancelabs
softdepend: [Vault]
commands:
   cm:
      description: Main command
      usage: /cm [action]
   colormatch:
      description: Main command
      usage: /colormatch [action]
