name: ColorMatch
main: com.comze_instancelabs.colormatch.Main
version: 1.7.7
author: instancelabs
depend: [Minigames]
commands:
   cm:
      description: Main command
      usage: /cm [action]
   colormatch:
      description: Main command
      usage: /colormatch [action]
