name: ColorMatch
main: au.com.addstar.colormatch.Main
version: ${plugin.version}
author: Narimm, addstarmc, instancelabs
depend: [Minigames]
commands:
   cm:
      description: Main command
      usage: /cm [action]
   colormatch:
      description: Main command
      usage: /colormatch [action]
